import { chromium } from '@playwright/test'
import { readFile } from 'node:fs/promises'
const browser = await chromium.launch({ headless: true, channel: 'chrome' })
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
const log = await readFile('/tmp/noteboard-dsh-3081.log', 'utf8')
const url = log.match(/http:\/\/127\.0\.0\.1:3081\/\?token=\S+/)?.[0]
if (!url) throw new Error('Missing local test server URL')
page.on('pageerror', (e) => console.log('PAGE ERROR', e.message))
page.on('console', (msg) => { if (msg.type() === 'error') console.log('CONSOLE', msg.text().slice(0, 400)) })
await page.goto(url)
await page.waitForTimeout(4000)
await page.getByRole('button', { name: '完成', exact: true }).click().catch(() => {})
console.log('BOOT', await page.evaluate(() => ({ boot: Object.keys(window.__DSH_BOOT__ ?? {}), loader: Object.keys(window.__ModuleLoader__ ?? {}) })))
await page.getByText('添加缩放画布查看所有便签按钮', { exact: true }).first().click()
await page.waitForTimeout(1500)
console.log('BEFORE CANVAS', (await page.locator('body').innerText()).slice(-5000))
console.log('BUTTONS', await page.getByRole('button').allTextContents())
await page.screenshot({ path: '/tmp/noteboard-before.png' })
await page.getByText('画布', { exact: true }).first().click({ timeout: 5000 }).catch((e) => console.log(e.message.slice(0, 150)))
await page.waitForTimeout(1000)
console.log((await page.locator('body').innerText()).slice(0, 5000))
console.log('GLOBALS', await page.evaluate(() => Object.keys(window).filter((x) => /dsh|ctx|module/i.test(x))))
await page.screenshot({ path: '/tmp/noteboard-host.png' })
await page.context().storageState({ path: '/tmp/noteboard-browser-state.json' })
await browser.close()
