import { chromium, expect } from '@playwright/test'
import { mkdtemp, readFile, rm, mkdir } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { buildApi } from '../src/commands.mjs'
const root = await mkdtemp(join(tmpdir(), 'noteboard-ui-'))
const api = buildApi(); await api.state(root)
await api.createNotes(root, { notes: [
  { title: '发布方案', body: '先邀请核心用户试用。\n\n- 收集反馈\n- 修复关键问题\n- 对外发布', tags: ['产品', '计划'], color: 'yellow', x: 0, y: 0 },
  { title: '设计原则与清晰的阅读层次', body: '**内容优先**，保持稳定的布局。\n让操作贴近正在处理的内容。', tags: ['设计'], color: 'blue', x: 300, y: 0 },
  { title: '用户访谈', body: '验证真实需求，记录原始材料和结论之间的关系。', tags: ['研究'], color: 'pink', x: 0, y: 220 },
  { title: '长内容与代码预览', body: '```ts\nconst selected = notes.filter(n => ids.has(n.id))\nconsole.log(selected)\n```\n' + '保留上下文，避免截断重要信息。'.repeat(12), tags: ['工程', '验证', '阅读'], color: 'green', x: 300, y: 220 },
] })
const browser = await chromium.launch({ headless: true, channel: 'chrome' })
const origin = process.env.NOTEBOARD_TEST_URL ?? 'http://127.0.0.1:3081'
const storage = JSON.parse(await readFile('/tmp/noteboard-browser-state.json', 'utf8'))
storage.origins = storage.origins.map((item) => ({ ...item, origin }))
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, storageState: storage })
const page = await context.newPage(), errors = []
page.on('pageerror', (e) => errors.push(e.message))
let failNextUpdate = false
await page.route('**/noteboard/api/rpc?*', async (route) => {
  const body = route.request().postDataJSON()
  if (failNextUpdate && body.method === 'updateNotes') { failNextUpdate = false; return route.fulfill({ status: 400, json: { error: '测试：保存失败' } }) }
  try { await route.fulfill({ json: await api[body.method](root, body.args ?? {}) }) }
  catch (e) { await route.fulfill({ status: 400, json: { error: e.message } }) }
})
const artifacts = join(process.cwd(), 'artifacts'); await mkdir(artifacts, { recursive: true })
try {
  const log = await readFile(`/tmp/noteboard-dsh-${new URL(origin).port}.log`, 'utf8').catch(() => '')
  await page.goto(log.match(/http:\/\/127\.0\.0\.1:\d+\/\?token=\S+/)?.[0] ?? origin)
  await page.getByRole('button', { name: '完成', exact: true }).click({ timeout: 1500 }).catch(() => {})
  await page.getByText('添加缩放画布查看所有便签按钮', { exact: true }).first().click()
  await page.getByText('画布', { exact: true }).first().click()
  await expect(page.locator('.nb-card')).toHaveCount(4)
  await page.getByRole('button', { name: '全览', exact: true }).click()
  await page.locator('.nb-card').filter({ hasText: '发布方案' }).click()
  await expect(page.locator('.nb-selection-tools')).toBeVisible()
  await page.screenshot({ path: join(artifacts, 'desktop-light.png') })
  await page.locator('.nb-card').filter({ hasText: '设计原则' }).click({ modifiers: ['Shift'] })
  await expect(page.locator('.nb-selected')).toHaveCount(2)
  await page.getByRole('button', { name: '换色', exact: true }).click()
  await page.getByRole('button', { name: '紫色', exact: true }).click()
  await expect(page.locator('.nb-card.color-purple')).toHaveCount(2)
  await page.getByRole('button', { name: '加入对话', exact: true }).click()
  await expect(page.getByText('已加入对话', { exact: true })).toBeVisible()
  console.log('REFERENCE DRAFT', await page.locator('[contenteditable=true]').innerText())
  await expect(page.locator('.nb-reference-chip')).toHaveCount(2)
  await page.getByRole('button', { name: '预览引用：发布方案', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '引用便签' })).toContainText('发布方案')
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: '移除引用：发布方案', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: '移除引用：设计原则与清晰的阅读层次', exact: true }).click()
  await expect(page.getByRole('button', { name: /^预览引用：/ })).toHaveCount(0)
  await page.getByRole('button', { name: '更多操作', exact: true }).click()
  await page.getByRole('button', { name: '从此画布移除', exact: true }).click()
  await expect(page.locator('.nb-card')).toHaveCount(2)
  await page.getByRole('button', { name: '搜索便签', exact: true }).click()
  await page.getByRole('button', { name: '未在此画布', exact: true }).click()
  await expect(page.locator('.nb-result')).toHaveCount(2)
  await page.getByRole('button', { name: '加入画布', exact: true }).first().click()
  await expect(page.locator('.nb-card')).toHaveCount(3)
  await page.getByRole('button', { name: '关闭侧栏', exact: true }).click()
  await page.getByRole('button', { name: '收起输入，返回画布工具', exact: true }).click()
  await page.getByRole('button', { name: '新建便签', exact: true }).click()
  await page.getByRole('textbox', { name: '标题', exact: true }).fill('新建验证')
  await page.getByRole('textbox', { name: '正文', exact: true }).fill('这是一张新便签')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.locator('.nb-card')).toHaveCount(4)
  await page.getByRole('button', { name: '全览', exact: true }).click()
  await page.locator('.nb-card').filter({ hasText: '新建验证' }).dblclick()
  await page.getByRole('textbox', { name: '正文', exact: true }).fill('失败也保留的草稿')
  failNextUpdate = true
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByText('测试：保存失败', { exact: true })).toBeVisible()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('textbox', { name: '正文', exact: true })).toHaveValue('失败也保留的草稿')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByText('对话', { exact: true }).first().click()
  await page.locator('[data-chat-anchor-key]').filter({ hasText: '帮我在画布上添加' }).first().evaluate((row) => {
    const walker = document.createTreeWalker(row, NodeFilter.SHOW_TEXT); let node
    while ((node = walker.nextNode())) if (node.textContent.includes('帮我在画布上添加')) { const range = document.createRange(); range.selectNodeContents(node); const sel = getSelection(); sel.removeAllRanges(); sel.addRange(range); break }
    document.dispatchEvent(new MouseEvent('mouseup', { bubbles: true }))
  })
  await page.getByRole('button', { name: '存入画布', exact: true }).click()
  await expect(page.getByRole('button', { name: '查看便签', exact: true })).toBeVisible()
  const saved = (await api.state(root)).notes.find((n) => n.source?.fragments?.length)
  console.log('SOURCE ANCHOR', saved?.source.fragments)
  await page.getByRole('button', { name: '查看便签', exact: true }).click()
  await expect(page.locator('.nb-card')).toHaveCount(5)
  await page.locator('.nb-card').filter({ hasText: '帮我在画布上添加' }).click()
  await page.getByRole('button', { name: '查看原文与依据', exact: true }).click()
  await page.getByRole('button', { name: '查看原文', exact: true }).click()
  await expect(page.locator('.nb-return')).toContainText('已定位原文')
  await page.screenshot({ path: join(artifacts, 'source-return.png') })
  await page.locator('.nb-return').click()
  await expect(page.locator('.nb-card')).toHaveCount(5)
  await page.evaluate(() => document.body.setAttribute('data-ds-dark-theme', ''))
  await page.getByRole('button', { name: '全览', exact: true }).click()
  await page.screenshot({ path: join(artifacts, 'desktop-dark.png') })
  await page.setViewportSize({ width: 720, height: 900 })
  await page.getByRole('button', { name: '全览', exact: true }).click()
  await page.screenshot({ path: join(artifacts, 'narrow-dark.png') })
  await page.setViewportSize({ width: 1440, height: 1000 })
  for (let i = 0; i < 14; i++) await page.getByRole('button', { name: '缩小', exact: true }).click()
  await expect(page.locator('.nb-zoom-value')).toHaveText('20%')
  for (let i = 0; i < 16; i++) await page.getByRole('button', { name: '放大', exact: true }).click()
  await expect(page.locator('.nb-zoom-value')).toHaveText('300%')
  await page.locator('.nb-zoom-value').click()
  await page.getByRole('button', { name: '复位视图', exact: true }).click()
  await expect(page.locator('.nb-zoom-value')).toHaveText('100%')
  const count = (await api.state(root)).canvas.nodes.length
  await api.createNotes(root, { notes: Array.from({ length: 200 - count }, (_, i) => ({ title: `性能验证 ${i}`, body: '200 张便签的框选与拖动', color: ['yellow','pink','blue','green','orange','purple','gray'][i % 7] })) })
  await page.reload()
  await page.getByText('画布', { exact: true }).first().click()
  await expect(page.locator('.nb-card')).toHaveCount(200)
  await page.getByRole('button', { name: '全览', exact: true }).click()
  const area = await page.locator('.nb-root').boundingBox()
  const start = Date.now()
  await page.mouse.move(area.x + 20, area.y + 150)
  await page.mouse.down()
  await page.mouse.move(area.x + area.width - 25, area.y + area.height - 65, { steps: 20 })
  await page.mouse.up()
  expect(await page.locator('.nb-selected').count()).toBeGreaterThan(10)
  console.log('200 NOTE MARQUEE MS', Date.now() - start)
  await page.screenshot({ path: join(artifacts, '200-notes-dark.png') })
  expect(errors).toEqual([])
  console.log('PASS: selection, batch color, reference insertion, removal/recovery, creation, save failure, source capture/navigation, themes')
} finally { await page.screenshot({ path: join(artifacts, 'last-state.png') }); await browser.close(); await rm(root, { recursive: true, force: true }) }
